version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chetan
      POSTGRES_DB: chetan
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:chetan@db:5432/chetan
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
